### ISSUE TITLE
Double tooltips

### ISSUE THREAD

**Issue by randyaskin** [PredixDev/px-vis-pie-chart#11]
When you hover over a segment of the pie/donut, the black tooltip pops up. If you then click, it rotates to the top and the white popover appears, but if you don't move the mouse, the black tooltip is still present, so you end up with duplicate tooltips. The black one should disappear on click.

<img width="386" alt="screen shot 2016-08-26 at 1 26 29 pm" src="https://cloud.githubusercontent.com/assets/2130613/18019426/e2b0f204-6b90-11e6-85ea-290f03635b9e.png">

**Comment by benoitjchevalier** [comment]
Fix coming in new major version

**Comment by benoitjchevalier** [comment]
fixed in new major

**Comment by davidsteinberger** [comment]
I just experienced that issue on recent versions. Can we reopen that issue? In addition to that the white popover gets truncated. Is there any way to workaround that?

![screen shot 2017-02-16 at 15 19 11](https://cloud.githubusercontent.com/assets/385430/23024745/c6ff4688-f45b-11e6-9928-8530d2ec3770.png)

**Comment by benoitjchevalier** [comment]
This should be fixed in the new 1.0.0, which is still in beta (official release next week).

**Comment by davidsteinberger** [comment]
Yeah, but I did use master and still got that issue.

**Comment by benoitjchevalier** [comment]
I was editing my answer, you're fast ;).

The truncated popover is actually a popover issue which we were aware of, just realized it wasn't tracked so  I created https://github.com/PredixDev/px-popover/issues/7

If you're using master and seeing this then it does sound like an issue, reopening

**Comment by benoitjchevalier** [comment]
@davidsteinberger still seeing the issue? Can't seem to be able to reproduce

**Comment by davidsteinberger** [comment]
I still see that issue. On-click I get the white popover, on mouse-over (you may need several mouse-over & -out events) I get the black popover w/ the same content.

px-vis: 5367d5
px-vis-pie: 4ad986

**Comment by benoitjchevalier** [comment]
Oh I see. I don't think we're going to change that, what we were trying to solve in this case was the fact that if you clicked a slice and not move the mouse then the tooltip would still be there with the popover. Now when you click the tooltip is dismissed, but if you start moving again it will come back

**Comment by benoitjchevalier** [comment]
closing as we consider this fixed in v1.0.0
